# Generated by Django 4.2.4 on 2023-09-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_introduce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduce',
        ),
    ]
